{% set name = "moonrepo-moon" %}
{% set version = "1.27.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/moonrepo/moon/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6523c40c48daa6eba267be22039d26a8412960595478562b79646f33ba9b55fb

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - cargo-bundle-licenses
    # - openssl
    - make

test:
  commands:
    - moon --help

about:
  home: https://moonrepo.dev/
  summary: 'Build system for managing codebases'
  description: |
    A task runner and monorepo management tool for the web ecosystem, written in Rust.
    Supports JavaScript, TypeScript, Rust, Go, Ruby, and more <https://moonrepo.dev/docs#supported-languages>
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://moonrepo.dev/docs
  dev_url: https://github.com/moonrepo/moon

extra:
  recipe-maintainers:
    - corker
