bot:
  automerge: true
build_platform:
  linux_64: linux_64
  osx_64: osx_64
  osx_arm64: osx_64
  win_64: win_64
conda_build:
  pkg_format: '2'
conda_build_tool: mambabuild
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_64: azure
  linux_arm64: azure
  osx_64: azure
  osx_arm64: azure
  win_64: azure
test: native_and_emulated
